DROP TABLE IF EXISTS PUBLIC.users CASCADE;
DROP TABLE IF EXISTS PUBLIC.categories CASCADE;
DROP TABLE IF EXISTS PUBLIC.locations CASCADE;
DROP TABLE IF EXISTS PUBLIC.events CASCADE;
DROP TABLE IF EXISTS PUBLIC.requests CASCADE;
DROP TABLE IF EXISTS PUBLIC.compilations CASCADE;
DROP TABLE IF EXISTS PUBLIC.compilations_events CASCADE;
DROP TABLE IF EXISTS PUBLIC.likes CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     likes BIGINT,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
                                     /*CONSTRAINT fk_user_rating FOREIGN KEY (likes) REFERENCES likes (id)*/
);

CREATE TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     CONSTRAINT pk_category PRIMARY KEY (id),
                                     CONSTRAINT UQ_CATEGORY UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
                                    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
                                    lat NUMERIC,
                                    lon NUMERIC,
                                    CONSTRAINT pk_location PRIMARY KEY (id),
                                    UNIQUE (lat, lon)
);

CREATE TABLE IF NOT EXISTS likes (
                                     id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
                                     is_like BOOLEAN,
                                     like_owner_id BIGINT,
                                     user_id BIGINT,
                                     event_id  BIGINT,
                                     CONSTRAINT like_id PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS events (
                                    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
                                    annotation  varchar(2000),
                                    category_id  BIGINT,
                                    created TIMESTAMP WITHOUT TIME ZONE,
                                    event_date TIMESTAMP WITHOUT TIME ZONE,
                                    published TIMESTAMP WITHOUT TIME ZONE,
                                    description varchar(7000),
                                    location_id BIGINT,
                                    paid BOOLEAN,
                                    participant_limit BIGINT,
                                    request_moderation BOOLEAN,
                                    title varchar(120),
                                    state varchar(30),
                                    user_id BIGINT,
                                    like_id BIGINT,
                                    CONSTRAINT pk_event PRIMARY KEY (id),
                                    CONSTRAINT fk_event_to_cat FOREIGN KEY (category_id) REFERENCES categories (id),
                                    CONSTRAINT fk_event_to_loc FOREIGN KEY (location_id) REFERENCES locations (id),
                                    CONSTRAINT fk_event_to_user FOREIGN KEY (user_id) REFERENCES users (id),
                                    CONSTRAINT fk_event_likes FOREIGN KEY (like_id) REFERENCES likes (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                    id    BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
                                    event_id  BIGINT,
                                    created TIMESTAMP WITHOUT TIME ZONE,
                                    status varchar(30),
                                    user_id BIGINT,
                                    CONSTRAINT pk_request PRIMARY KEY (id),
                                    CONSTRAINT fk_request_to_event FOREIGN KEY (event_id) REFERENCES events (id),
                                    CONSTRAINT fk_request_to_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations (
                                    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    pinned BOOLEAN,
                                    title  varchar(50)
);

CREATE TABLE IF NOT EXISTS compilations_events (
                                    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    event_id  BIGINT,
                                    comp_id BIGINT,
                                    CONSTRAINT fk_to_event FOREIGN KEY (event_id) REFERENCES events (id),
                                    CONSTRAINT fk_to_comp FOREIGN KEY (comp_id) REFERENCES compilations (id)
);


/*
CREATE TABLE IF NOT EXISTS likes_user (
                                   id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                   owner_id  BIGINT,
                                   user_id BIGINT,
                                   CONSTRAINT fk_likes_owner FOREIGN KEY (owner_id) REFERENCES users (id),
                                   CONSTRAINT fk_likes_to_user FOREIGN KEY (user_id) REFERENCES users (id)
);*/